# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'InsertWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_insertWindow(object):
    def setupUi(self, insertWindow):
        insertWindow.setObjectName("insertWindow")
        insertWindow.resize(378, 425)
        self.phoneEdit = QtWidgets.QLineEdit(insertWindow)
        self.phoneEdit.setGeometry(QtCore.QRect(150, 130, 160, 40))
        self.phoneEdit.setObjectName("phoneEdit")
        self.comboBox = QtWidgets.QComboBox(insertWindow)
        self.comboBox.setGeometry(QtCore.QRect(150, 200, 160, 40))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.pushButton = QtWidgets.QPushButton(insertWindow)
        self.pushButton.setGeometry(QtCore.QRect(70, 307, 241, 51))
        self.pushButton.setObjectName("pushButton")
        self.nameEdit = QtWidgets.QLineEdit(insertWindow)
        self.nameEdit.setGeometry(QtCore.QRect(150, 60, 160, 40))
        self.nameEdit.setObjectName("nameEdit")
        self.label = QtWidgets.QLabel(insertWindow)
        self.label.setGeometry(QtCore.QRect(60, 70, 72, 15))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(insertWindow)
        self.label_2.setGeometry(QtCore.QRect(60, 140, 72, 15))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(insertWindow)
        self.label_3.setGeometry(QtCore.QRect(60, 215, 72, 15))
        self.label_3.setObjectName("label_3")

        self.retranslateUi(insertWindow)
        QtCore.QMetaObject.connectSlotsByName(insertWindow)

    def retranslateUi(self, insertWindow):
        _translate = QtCore.QCoreApplication.translate
        insertWindow.setWindowTitle(_translate("insertWindow", "添加员工"))
        self.comboBox.setItemText(0, _translate("insertWindow", "市场部"))
        self.comboBox.setItemText(1, _translate("insertWindow", "研发部"))
        self.comboBox.setItemText(2, _translate("insertWindow", "运维部"))
        self.pushButton.setText(_translate("insertWindow", "添加"))
        self.label.setText(_translate("insertWindow", "姓名"))
        self.label_2.setText(_translate("insertWindow", "电话"))
        self.label_3.setText(_translate("insertWindow", "部门"))
