# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UpdateWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_UpdateWindow(object):
    def setupUi(self, UpdateWindow):
        UpdateWindow.setObjectName("UpdateWindow")
        UpdateWindow.resize(376, 406)
        self.idLab = QtWidgets.QLabel(UpdateWindow)
        self.idLab.setGeometry(QtCore.QRect(100, 30, 121, 41))
        self.idLab.setObjectName("idLab")
        self.nameEdit = QtWidgets.QLineEdit(UpdateWindow)
        self.nameEdit.setGeometry(QtCore.QRect(100, 100, 161, 41))
        self.nameEdit.setObjectName("nameEdit")
        self.comboBox = QtWidgets.QComboBox(UpdateWindow)
        self.comboBox.setGeometry(QtCore.QRect(100, 240, 161, 41))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.updateBtn = QtWidgets.QPushButton(UpdateWindow)
        self.updateBtn.setGeometry(QtCore.QRect(100, 330, 161, 41))
        self.updateBtn.setObjectName("updateBtn")
        self.phoneEdit = QtWidgets.QLineEdit(UpdateWindow)
        self.phoneEdit.setGeometry(QtCore.QRect(100, 170, 161, 41))
        self.phoneEdit.setObjectName("phoneEdit")

        self.retranslateUi(UpdateWindow)
        QtCore.QMetaObject.connectSlotsByName(UpdateWindow)

    def retranslateUi(self, UpdateWindow):
        _translate = QtCore.QCoreApplication.translate
        UpdateWindow.setWindowTitle(_translate("UpdateWindow", "编辑员工信息"))
        self.idLab.setText(_translate("UpdateWindow", "TextLabel"))
        self.comboBox.setItemText(0, _translate("UpdateWindow", "市场部"))
        self.comboBox.setItemText(1, _translate("UpdateWindow", "研发部"))
        self.comboBox.setItemText(2, _translate("UpdateWindow", "运维部"))
        self.updateBtn.setText(_translate("UpdateWindow", "修改"))
