# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'QQForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(400, 560)
        MainWindow.setStyleSheet("font-family:微软雅黑;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.qqEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.qqEdit.setGeometry(QtCore.QRect(40, 180, 320, 55))
        self.qqEdit.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.qqEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.qqEdit.setObjectName("qqEdit")
        self.pwdEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.pwdEdit.setGeometry(QtCore.QRect(40, 250, 320, 55))
        self.pwdEdit.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.pwdEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.pwdEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.pwdEdit.setObjectName("pwdEdit")
        self.radioButton = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton.setGeometry(QtCore.QRect(40, 330, 311, 19))
        self.radioButton.setStyleSheet("color:#999999")
        self.radioButton.setObjectName("radioButton")
        self.logBtn = QtWidgets.QPushButton(self.centralwidget)
        self.logBtn.setGeometry(QtCore.QRect(40, 380, 320, 45))
        self.logBtn.setObjectName("logBtn")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(120, 480, 71, 20))
        self.label.setStyleSheet("color:#2d77e5;font-size:16px;")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(205, 480, 72, 20))
        self.label_2.setStyleSheet("color:#2d77e5;font-size:16px;")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(192, 480, 21, 20))
        self.label_3.setStyleSheet("color:#999999")
        self.label_3.setObjectName("label_3")
        self.headWidget = QtWidgets.QWidget(self.centralwidget)
        self.headWidget.setGeometry(QtCore.QRect(150, 40, 100, 100))
        self.headWidget.setObjectName("headWidget")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.qqEdit.setPlaceholderText(_translate("MainWindow", "输入QQ号"))
        self.pwdEdit.setPlaceholderText(_translate("MainWindow", "输入QQ密码"))
        self.radioButton.setText(_translate("MainWindow", "已阅读并同意服务协议和QQ隐私保护指引"))
        self.logBtn.setText(_translate("MainWindow", "登录"))
        self.label.setText(_translate("MainWindow", "扫码登录"))
        self.label_2.setText(_translate("MainWindow", "更多选项"))
        self.label_3.setText(_translate("MainWindow", "|"))
