# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SubWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SubWindow(object):
    def setupUi(self, SubWindow):
        SubWindow.setObjectName("SubWindow")
        SubWindow.resize(400, 300)
        self.pushButton = QtWidgets.QPushButton(SubWindow)
        self.pushButton.setGeometry(QtCore.QRect(100, 180, 211, 71))
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(SubWindow)
        QtCore.QMetaObject.connectSlotsByName(SubWindow)

    def retranslateUi(self, SubWindow):
        _translate = QtCore.QCoreApplication.translate
        SubWindow.setWindowTitle(_translate("SubWindow", "子窗口"))
        self.pushButton.setText(_translate("SubWindow", "返回主窗口"))
