# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LoginWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LoginWindow(object):
    def setupUi(self, LoginWindow):
        LoginWindow.setObjectName("LoginWindow")
        LoginWindow.resize(400, 300)
        self.pushButton = QtWidgets.QPushButton(LoginWindow)
        self.pushButton.setGeometry(QtCore.QRect(90, 200, 221, 41))
        self.pushButton.setObjectName("pushButton")
        self.usernameEdit = QtWidgets.QLineEdit(LoginWindow)
        self.usernameEdit.setGeometry(QtCore.QRect(90, 70, 221, 31))
        self.usernameEdit.setObjectName("usernameEdit")
        self.passwordEdit = QtWidgets.QLineEdit(LoginWindow)
        self.passwordEdit.setGeometry(QtCore.QRect(90, 120, 221, 31))
        self.passwordEdit.setObjectName("passwordEdit")

        self.retranslateUi(LoginWindow)
        QtCore.QMetaObject.connectSlotsByName(LoginWindow)

    def retranslateUi(self, LoginWindow):
        _translate = QtCore.QCoreApplication.translate
        LoginWindow.setWindowTitle(_translate("LoginWindow", "登录"))
        self.pushButton.setText(_translate("LoginWindow", "登录"))
