# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MyForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(822, 578)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.leftFrame = QtWidgets.QFrame(self.centralwidget)
        self.leftFrame.setGeometry(QtCore.QRect(0, 0, 171, 581))
        self.leftFrame.setStyleSheet("QFrame{\n"
"    background-color:#f0f3f6;\n"
"}\n"
"QPushButton{\n"
"    border:none;\n"
"    border-radius:10px;\n"
"    font-size:18px;\n"
"    font-family:微软雅黑;\n"
"    color:#4e5669\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:#e4e8ec;\n"
"    border-radius:10px;\n"
"}")
        self.leftFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.leftFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.leftFrame.setObjectName("leftFrame")
        self.logoLab = QtWidgets.QLabel(self.leftFrame)
        self.logoLab.setGeometry(QtCore.QRect(20, 10, 125, 106))
        self.logoLab.setObjectName("logoLab")
        self.casualBtn = QtWidgets.QPushButton(self.leftFrame)
        self.casualBtn.setGeometry(QtCore.QRect(25, 150, 121, 51))
        self.casualBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.casualBtn.setStyleSheet("background-color:#fc3d49;\n"
"color:#fff;")
        self.casualBtn.setObjectName("casualBtn")
        self.myMusicBtn = QtWidgets.QPushButton(self.leftFrame)
        self.myMusicBtn.setGeometry(QtCore.QRect(25, 220, 121, 51))
        self.myMusicBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.myMusicBtn.setObjectName("myMusicBtn")
        self.topFrame = QtWidgets.QFrame(self.centralwidget)
        self.topFrame.setGeometry(QtCore.QRect(170, 0, 651, 51))
        self.topFrame.setStyleSheet("QFrame{\n"
"    background-color:#f7f9fc\n"
"}\n"
"QPushButton{\n"
"    border:none;\n"
"}\n"
"QPushButton:hover{\n"
"    font-weight:700\n"
"}")
        self.topFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.topFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.topFrame.setObjectName("topFrame")
        self.minBtn = QtWidgets.QPushButton(self.topFrame)
        self.minBtn.setGeometry(QtCore.QRect(570, 10, 20, 20))
        self.minBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.minBtn.setObjectName("minBtn")
        self.exitBtn = QtWidgets.QPushButton(self.topFrame)
        self.exitBtn.setGeometry(QtCore.QRect(610, 10, 20, 20))
        self.exitBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.exitBtn.setObjectName("exitBtn")
        self.bottomFrame = QtWidgets.QFrame(self.centralwidget)
        self.bottomFrame.setGeometry(QtCore.QRect(0, 479, 821, 100))
        self.bottomFrame.setStyleSheet("QFrame{\n"
"    background-color:#fafafa\n"
"}\n"
"QPushButton{\n"
"    border:none;\n"
"}")
        self.bottomFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.bottomFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.bottomFrame.setObjectName("bottomFrame")
        self.playBtn = QtWidgets.QPushButton(self.bottomFrame)
        self.playBtn.setGeometry(QtCore.QRect(380, 10, 50, 50))
        self.playBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.playBtn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/res/imgs/icon/zanting.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.playBtn.setIcon(icon)
        self.playBtn.setIconSize(QtCore.QSize(50, 50))
        self.playBtn.setObjectName("playBtn")
        self.prevBtn = QtWidgets.QPushButton(self.bottomFrame)
        self.prevBtn.setGeometry(QtCore.QRect(340, 25, 20, 20))
        self.prevBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.prevBtn.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/res/imgs/icon/shangyiqu.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.prevBtn.setIcon(icon1)
        self.prevBtn.setObjectName("prevBtn")
        self.nextBtn = QtWidgets.QPushButton(self.bottomFrame)
        self.nextBtn.setGeometry(QtCore.QRect(450, 25, 20, 20))
        self.nextBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.nextBtn.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/res/imgs/icon/xiayiqu.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.nextBtn.setIcon(icon2)
        self.nextBtn.setObjectName("nextBtn")
        self.playerSlider = QtWidgets.QSlider(self.bottomFrame)
        self.playerSlider.setGeometry(QtCore.QRect(280, 60, 251, 22))
        self.playerSlider.setOrientation(QtCore.Qt.Horizontal)
        self.playerSlider.setObjectName("playerSlider")
        self.volumeSlider = QtWidgets.QSlider(self.bottomFrame)
        self.volumeSlider.setGeometry(QtCore.QRect(710, 30, 81, 22))
        self.volumeSlider.setProperty("value", 50)
        self.volumeSlider.setOrientation(QtCore.Qt.Horizontal)
        self.volumeSlider.setObjectName("volumeSlider")
        self.songInfoLab = QtWidgets.QLabel(self.bottomFrame)
        self.songInfoLab.setGeometry(QtCore.QRect(30, 30, 151, 41))
        self.songInfoLab.setText("")
        self.songInfoLab.setObjectName("songInfoLab")
        self.timeLab = QtWidgets.QLabel(self.bottomFrame)
        self.timeLab.setGeometry(QtCore.QRect(230, 60, 41, 16))
        self.timeLab.setObjectName("timeLab")
        self.durationLab = QtWidgets.QLabel(self.bottomFrame)
        self.durationLab.setGeometry(QtCore.QRect(540, 60, 72, 15))
        self.durationLab.setText("")
        self.durationLab.setObjectName("durationLab")
        self.volumeBtn = QtWidgets.QPushButton(self.bottomFrame)
        self.volumeBtn.setGeometry(QtCore.QRect(680, 25, 31, 28))
        self.volumeBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.volumeBtn.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/res/imgs/icon/yinliangjian.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.volumeBtn.setIcon(icon3)
        self.volumeBtn.setObjectName("volumeBtn")
        self.playModeBtn = QtWidgets.QPushButton(self.bottomFrame)
        self.playModeBtn.setGeometry(QtCore.QRect(660, 30, 20, 20))
        self.playModeBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.playModeBtn.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/res/imgs/icon/liebiaoxunhuan.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.playModeBtn.setIcon(icon4)
        self.playModeBtn.setObjectName("playModeBtn")
        self.rightFrame = QtWidgets.QFrame(self.centralwidget)
        self.rightFrame.setGeometry(QtCore.QRect(170, 50, 651, 531))
        self.rightFrame.setStyleSheet("background-color:#f7f9fc")
        self.rightFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.rightFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.rightFrame.setObjectName("rightFrame")
        self.stackedWidget = QtWidgets.QStackedWidget(self.rightFrame)
        self.stackedWidget.setGeometry(QtCore.QRect(10, 0, 641, 431))
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.lab1 = QtWidgets.QLabel(self.page)
        self.lab1.setGeometry(QtCore.QRect(50, 10, 200, 200))
        self.lab1.setObjectName("lab1")
        self.lab3 = QtWidgets.QLabel(self.page)
        self.lab3.setGeometry(QtCore.QRect(50, 230, 200, 200))
        self.lab3.setObjectName("lab3")
        self.lab2 = QtWidgets.QLabel(self.page)
        self.lab2.setGeometry(QtCore.QRect(330, 10, 200, 200))
        self.lab2.setObjectName("lab2")
        self.lab4 = QtWidgets.QLabel(self.page)
        self.lab4.setGeometry(QtCore.QRect(330, 230, 200, 200))
        self.lab4.setObjectName("lab4")
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.chooseDirLink = QtWidgets.QCommandLinkButton(self.page_2)
        self.chooseDirLink.setGeometry(QtCore.QRect(0, 10, 121, 31))
        self.chooseDirLink.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.chooseDirLink.setStyleSheet("border:none")
        self.chooseDirLink.setObjectName("chooseDirLink")
        self.listWidget = QtWidgets.QListWidget(self.page_2)
        self.listWidget.setGeometry(QtCore.QRect(10, 70, 681, 361))
        self.listWidget.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.listWidget.setStyleSheet("border:none")
        self.listWidget.setObjectName("listWidget")
        self.stackedWidget.addWidget(self.page_2)
        self.leftFrame.raise_()
        self.topFrame.raise_()
        self.rightFrame.raise_()
        self.bottomFrame.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.logoLab.setText(_translate("MainWindow", "TextLabel"))
        self.casualBtn.setText(_translate("MainWindow", "随便看看"))
        self.myMusicBtn.setText(_translate("MainWindow", "本地音乐"))
        self.minBtn.setText(_translate("MainWindow", "-"))
        self.exitBtn.setText(_translate("MainWindow", "×"))
        self.timeLab.setText(_translate("MainWindow", "00:00"))
        self.lab1.setText(_translate("MainWindow", "TextLabel"))
        self.lab3.setText(_translate("MainWindow", "TextLabel"))
        self.lab2.setText(_translate("MainWindow", "TextLabel"))
        self.lab4.setText(_translate("MainWindow", "TextLabel"))
        self.chooseDirLink.setText(_translate("MainWindow", "选择目录"))
import resources_rc
